trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md

jobs:
- template: ../Templates/build-publish-dotnetcore.yml
  parameters:
    name: BuildWebApp
    project: '**/ToDoListService/*.csproj'
    buildConfiguration: Debug
    artifactName: TodoList.Service
    vmImage: 'vs2017-win2016'